export type TaskCategory =
  | "GUEST_REQUEST"
  | "ROOM_CLEANING"
  | "COMMON_AREA"
  | "PREVENTIVE_MAINTENANCE"
  | "TIME_SENSITIVE"

export type Department = "housekeeping" | "maintenance"

export type Priority = "urgent" | "high" | "medium" | "low"

export interface TaskDefinition {
  id: string
  name: string
  category: TaskCategory
  department: Department
  duration: number // minutes
  priority: Priority
  photoRequired: boolean
  photoCount: number
  keywords: string[] // for search matching
  requiresRoom: boolean
  requiresACLocation?: boolean
  deadline?: string // for time-sensitive tasks (HH:MM format)
}

export const TASK_DEFINITIONS: TaskDefinition[] = [
  // GUEST REQUESTS (19 tasks)
  {
    id: "guest-light-not-working",
    name: "Light Not Working",
    category: "GUEST_REQUEST",
    department: "maintenance",
    duration: 15,
    priority: "urgent",
    photoRequired: true,
    photoCount: 1,
    keywords: ["light", "bulb", "lamp", "not working", "broken"],
    requiresRoom: true,
  },
  {
    id: "guest-electricity-issue",
    name: "Electricity Not There",
    category: "GUEST_REQUEST",
    department: "maintenance",
    duration: 30,
    priority: "urgent",
    photoRequired: true,
    photoCount: 2,
    keywords: ["electricity", "power", "no power", "blackout"],
    requiresRoom: true,
  },
  {
    id: "guest-ac-not-working",
    name: "AC Not Working",
    category: "GUEST_REQUEST",
    department: "maintenance",
    duration: 30,
    priority: "urgent",
    photoRequired: true,
    photoCount: 2,
    keywords: ["ac", "air conditioning", "cooling", "not cold", "not working"],
    requiresRoom: true,
  },
  {
    id: "guest-fan-not-working",
    name: "Fan Not Working",
    category: "GUEST_REQUEST",
    department: "maintenance",
    duration: 15,
    priority: "urgent",
    photoRequired: true,
    photoCount: 1,
    keywords: ["fan", "not working", "broken"],
    requiresRoom: true,
  },
  {
    id: "guest-tv-not-working",
    name: "TV Not Working",
    category: "GUEST_REQUEST",
    department: "maintenance",
    duration: 20,
    priority: "urgent",
    photoRequired: true,
    photoCount: 1,
    keywords: ["tv", "television", "not working", "no signal"],
    requiresRoom: true,
  },
  {
    id: "guest-water-temperature",
    name: "No Hot/Cold Water",
    category: "GUEST_REQUEST",
    department: "maintenance",
    duration: 25,
    priority: "urgent",
    photoRequired: true,
    photoCount: 2,
    keywords: ["water", "hot water", "cold water", "temperature"],
    requiresRoom: true,
  },
  {
    id: "guest-amenities-missing",
    name: "Room Amenities Missing",
    category: "GUEST_REQUEST",
    department: "housekeeping",
    duration: 10,
    priority: "high",
    photoRequired: true,
    photoCount: 1,
    keywords: ["amenities", "missing", "soap dish", "hangers"],
    requiresRoom: true,
  },
  {
    id: "guest-toiletries-missing",
    name: "Toiletries Missing",
    category: "GUEST_REQUEST",
    department: "housekeeping",
    duration: 10,
    priority: "high",
    photoRequired: true,
    photoCount: 1,
    keywords: ["toiletries", "soap", "shampoo", "missing"],
    requiresRoom: true,
  },
  {
    id: "guest-linen-bad",
    name: "Linen Bad (Holes/Spots/Stains)",
    category: "GUEST_REQUEST",
    department: "housekeeping",
    duration: 15,
    priority: "urgent",
    photoRequired: true,
    photoCount: 2,
    keywords: ["linen", "sheets", "bedding", "holes", "stains", "spots", "dirty"],
    requiresRoom: true,
  },
  {
    id: "guest-towel-missing",
    name: "Towel/Bath Mat Missing",
    category: "GUEST_REQUEST",
    department: "housekeeping",
    duration: 10,
    priority: "high",
    photoRequired: true,
    photoCount: 1,
    keywords: ["towel", "bath mat", "missing"],
    requiresRoom: true,
  },
  {
    id: "guest-water-bottle-missing",
    name: "Water Bottle Missing",
    category: "GUEST_REQUEST",
    department: "housekeeping",
    duration: 5,
    priority: "medium",
    photoRequired: true,
    photoCount: 1,
    keywords: ["water", "bottle", "missing"],
    requiresRoom: true,
  },
  {
    id: "guest-room-smell",
    name: "Room Smell",
    category: "GUEST_REQUEST",
    department: "housekeeping",
    duration: 20,
    priority: "high",
    photoRequired: true,
    photoCount: 1,
    keywords: ["smell", "odor", "stink", "bad smell"],
    requiresRoom: true,
  },
  {
    id: "guest-room-not-cleaned",
    name: "Room Not Cleaned",
    category: "GUEST_REQUEST",
    department: "housekeeping",
    duration: 45,
    priority: "urgent",
    photoRequired: true,
    photoCount: 3,
    keywords: ["not cleaned", "dirty", "messy"],
    requiresRoom: true,
  },
  {
    id: "guest-extra-towel",
    name: "Extra Towel",
    category: "GUEST_REQUEST",
    department: "housekeeping",
    duration: 5,
    priority: "medium",
    photoRequired: true,
    photoCount: 1,
    keywords: ["extra", "towel", "more towels"],
    requiresRoom: true,
  },
  {
    id: "guest-extra-pillow",
    name: "Extra Pillow",
    category: "GUEST_REQUEST",
    department: "housekeeping",
    duration: 5,
    priority: "medium",
    photoRequired: true,
    photoCount: 1,
    keywords: ["extra", "pillow", "more pillows"],
    requiresRoom: true,
  },
  {
    id: "guest-extra-bed",
    name: "Extra Bed",
    category: "GUEST_REQUEST",
    department: "housekeeping",
    duration: 30,
    priority: "high",
    photoRequired: true,
    photoCount: 2,
    keywords: ["extra", "bed", "additional bed"],
    requiresRoom: true,
  },
  {
    id: "guest-extra-water-bottle",
    name: "Extra Water Bottle",
    category: "GUEST_REQUEST",
    department: "housekeeping",
    duration: 5,
    priority: "medium",
    photoRequired: true,
    photoCount: 1,
    keywords: ["extra", "water", "bottle", "more water"],
    requiresRoom: true,
  },
  {
    id: "guest-extra-amenities",
    name: "Extra Room Amenities",
    category: "GUEST_REQUEST",
    department: "housekeeping",
    duration: 10,
    priority: "medium",
    photoRequired: true,
    photoCount: 1,
    keywords: ["extra", "amenities", "more amenities"],
    requiresRoom: true,
  },
  {
    id: "guest-appliance-request",
    name: "Appliance Request",
    category: "GUEST_REQUEST",
    department: "housekeeping",
    duration: 10,
    priority: "medium",
    photoRequired: true,
    photoCount: 1,
    keywords: ["appliance", "kettle", "microwave", "hair dryer", "iron"],
    requiresRoom: true,
  },

  // ROOM CLEANING (3 types)
  {
    id: "room-checkout-cleaning",
    name: "Checkout Room Cleaning",
    category: "ROOM_CLEANING",
    department: "housekeeping",
    duration: 45,
    priority: "high",
    photoRequired: true,
    photoCount: 3,
    keywords: ["checkout", "room", "cleaning"],
    requiresRoom: true,
  },
  {
    id: "room-stayover-cleaning",
    name: "Stay-over Room Cleaning",
    category: "ROOM_CLEANING",
    department: "housekeeping",
    duration: 30,
    priority: "medium",
    photoRequired: true,
    photoCount: 2,
    keywords: ["stayover", "stay over", "room", "cleaning"],
    requiresRoom: true,
  },
  {
    id: "room-vacant-cleaning",
    name: "Vacant Room Deep Cleaning",
    category: "ROOM_CLEANING",
    department: "housekeeping",
    duration: 60,
    priority: "low",
    photoRequired: true,
    photoCount: 3,
    keywords: ["vacant", "deep", "cleaning", "empty room"],
    requiresRoom: true,
  },

  // COMMON AREA CLEANING (17 areas)
  {
    id: "common-parking",
    name: "Internal Roads and Parking Cleaning",
    category: "COMMON_AREA",
    department: "housekeeping",
    duration: 30,
    priority: "medium",
    photoRequired: true,
    photoCount: 1,
    keywords: ["parking", "roads", "internal roads"],
    requiresRoom: false,
  },
  {
    id: "common-lawn",
    name: "Lawn Cleaning",
    category: "COMMON_AREA",
    department: "housekeeping",
    duration: 45,
    priority: "medium",
    photoRequired: true,
    photoCount: 1,
    keywords: ["lawn", "grass", "garden"],
    requiresRoom: false,
  },
  {
    id: "common-play-area",
    name: "Kid's Play Area Cleaning",
    category: "COMMON_AREA",
    department: "housekeeping",
    duration: 20,
    priority: "medium",
    photoRequired: true,
    photoCount: 2,
    keywords: ["kids", "play area", "playground"],
    requiresRoom: false,
  },
  {
    id: "common-a-corridor",
    name: "A Block Corridor Cleaning",
    category: "COMMON_AREA",
    department: "housekeeping",
    duration: 25,
    priority: "medium",
    photoRequired: true,
    photoCount: 1,
    keywords: ["corridor", "a block", "hallway"],
    requiresRoom: false,
  },
  {
    id: "common-a-guest-stairs",
    name: "A Block Guest Staircase Cleaning",
    category: "COMMON_AREA",
    department: "housekeeping",
    duration: 20,
    priority: "medium",
    photoRequired: true,
    photoCount: 1,
    keywords: ["staircase", "stairs", "a block", "guest"],
    requiresRoom: false,
  },
  {
    id: "common-a-staff-stairs",
    name: "A Block Staff Staircase Cleaning",
    category: "COMMON_AREA",
    department: "housekeeping",
    duration: 15,
    priority: "low",
    photoRequired: true,
    photoCount: 1,
    keywords: ["staircase", "stairs", "a block", "staff"],
    requiresRoom: false,
  },
  {
    id: "common-b-corridor",
    name: "B Block Corridor Cleaning",
    category: "COMMON_AREA",
    department: "housekeeping",
    duration: 25,
    priority: "medium",
    photoRequired: true,
    photoCount: 1,
    keywords: ["corridor", "b block", "hallway"],
    requiresRoom: false,
  },
  {
    id: "common-b-guest-stairs",
    name: "B Block Guest Staircase Cleaning",
    category: "COMMON_AREA",
    department: "housekeeping",
    duration: 20,
    priority: "medium",
    photoRequired: true,
    photoCount: 1,
    keywords: ["staircase", "stairs", "b block", "guest"],
    requiresRoom: false,
  },
  {
    id: "common-b-staff-stairs",
    name: "B Block Staff Staircase Cleaning",
    category: "COMMON_AREA",
    department: "housekeeping",
    duration: 15,
    priority: "low",
    photoRequired: true,
    photoCount: 1,
    keywords: ["staircase", "stairs", "b block", "staff"],
    requiresRoom: false,
  },
  {
    id: "common-porch",
    name: "Porch Cleaning",
    category: "COMMON_AREA",
    department: "housekeeping",
    duration: 20,
    priority: "high",
    photoRequired: true,
    photoCount: 2,
    keywords: ["porch", "ramp", "entrance"],
    requiresRoom: false,
  },
  {
    id: "common-reception",
    name: "Reception Cleaning",
    category: "COMMON_AREA",
    department: "housekeeping",
    duration: 20,
    priority: "high",
    photoRequired: true,
    photoCount: 2,
    keywords: ["reception", "front desk", "lobby"],
    requiresRoom: false,
  },
  {
    id: "common-restaurant",
    name: "Restaurant Cleaning",
    category: "COMMON_AREA",
    department: "housekeeping",
    duration: 45,
    priority: "high",
    photoRequired: true,
    photoCount: 2,
    keywords: ["restaurant", "dining", "eating area"],
    requiresRoom: false,
  },
  {
    id: "common-public-toilet",
    name: "Public Toilet Cleaning",
    category: "COMMON_AREA",
    department: "housekeeping",
    duration: 25,
    priority: "high",
    photoRequired: true,
    photoCount: 2,
    keywords: ["toilet", "bathroom", "restroom", "public"],
    requiresRoom: false,
  },
  {
    id: "common-banquet",
    name: "Banquet Hall Cleaning",
    category: "COMMON_AREA",
    department: "housekeeping",
    duration: 40,
    priority: "medium",
    photoRequired: true,
    photoCount: 2,
    keywords: ["banquet", "hall", "event space"],
    requiresRoom: false,
  },
  {
    id: "common-b-lobby",
    name: "B Block Lobby Cleaning",
    category: "COMMON_AREA",
    department: "housekeeping",
    duration: 20,
    priority: "high",
    photoRequired: true,
    photoCount: 2,
    keywords: ["lobby", "b block", "entrance"],
    requiresRoom: false,
  },
  {
    id: "common-lift-lobby",
    name: "Lift Lobby Cleaning",
    category: "COMMON_AREA",
    department: "housekeeping",
    duration: 15,
    priority: "medium",
    photoRequired: true,
    photoCount: 1,
    keywords: ["lift", "lobby", "elevator"],
    requiresRoom: false,
  },
  {
    id: "common-games",
    name: "Indoor Games Area Cleaning",
    category: "COMMON_AREA",
    department: "housekeeping",
    duration: 25,
    priority: "medium",
    photoRequired: true,
    photoCount: 1,
    keywords: ["games", "indoor", "play area"],
    requiresRoom: false,
  },

  // TIME-SENSITIVE (5 tasks)
  {
    id: "time-reception-morning",
    name: "Reception and Porch Cleaning",
    category: "TIME_SENSITIVE",
    department: "housekeeping",
    duration: 25,
    priority: "urgent",
    photoRequired: true,
    photoCount: 2,
    keywords: ["reception", "porch", "morning"],
    requiresRoom: false,
    deadline: "07:30",
  },
  {
    id: "time-restaurant-morning",
    name: "Restaurant/Banquet Hall Morning Cleaning",
    category: "TIME_SENSITIVE",
    department: "housekeeping",
    duration: 45,
    priority: "urgent",
    photoRequired: true,
    photoCount: 2,
    keywords: ["restaurant", "banquet", "morning", "breakfast"],
    requiresRoom: false,
    deadline: "08:15",
  },
  {
    id: "time-toilet-morning",
    name: "Public Toilets Morning Cleaning",
    category: "TIME_SENSITIVE",
    department: "housekeeping",
    duration: 25,
    priority: "urgent",
    photoRequired: true,
    photoCount: 2,
    keywords: ["toilet", "bathroom", "morning"],
    requiresRoom: false,
    deadline: "08:15",
  },
  {
    id: "time-pool-morning",
    name: "Swimming Pool/Waterpark Vacuuming",
    category: "TIME_SENSITIVE",
    department: "housekeeping",
    duration: 150,
    priority: "urgent",
    photoRequired: true,
    photoCount: 2,
    keywords: ["pool", "swimming", "waterpark", "vacuuming"],
    requiresRoom: false,
    deadline: "09:00",
  },
  {
    id: "time-restaurant-after-breakfast",
    name: "Restaurant After Breakfast Cleaning",
    category: "TIME_SENSITIVE",
    department: "housekeeping",
    duration: 45,
    priority: "high",
    photoRequired: true,
    photoCount: 2,
    keywords: ["restaurant", "after breakfast", "lunch"],
    requiresRoom: false,
    deadline: "12:00",
  },

  // PREVENTIVE MAINTENANCE (6 types)
  {
    id: "maint-ac-indoor",
    name: "AC Indoor Unit Cleaning",
    category: "PREVENTIVE_MAINTENANCE",
    department: "maintenance",
    duration: 30,
    priority: "low",
    photoRequired: true,
    photoCount: 2,
    keywords: ["ac", "indoor", "maintenance", "preventive"],
    requiresRoom: true,
    requiresACLocation: true,
  },
  {
    id: "maint-ac-outdoor",
    name: "AC Outdoor Unit Cleaning",
    category: "PREVENTIVE_MAINTENANCE",
    department: "maintenance",
    duration: 45,
    priority: "low",
    photoRequired: true,
    photoCount: 2,
    keywords: ["ac", "outdoor", "maintenance", "preventive"],
    requiresRoom: true,
    requiresACLocation: true,
  },
  {
    id: "maint-fan",
    name: "Fan Cleaning",
    category: "PREVENTIVE_MAINTENANCE",
    department: "maintenance",
    duration: 15,
    priority: "low",
    photoRequired: true,
    photoCount: 2,
    keywords: ["fan", "maintenance", "preventive"],
    requiresRoom: true,
  },
  {
    id: "maint-exhaust",
    name: "Bathroom Exhaust Fan Cleaning",
    category: "PREVENTIVE_MAINTENANCE",
    department: "maintenance",
    duration: 20,
    priority: "low",
    photoRequired: true,
    photoCount: 2,
    keywords: ["exhaust", "bathroom", "fan", "maintenance"],
    requiresRoom: true,
  },
  {
    id: "maint-lift-a",
    name: "Lift Maintenance - A Block",
    category: "PREVENTIVE_MAINTENANCE",
    department: "maintenance",
    duration: 60,
    priority: "medium",
    photoRequired: true,
    photoCount: 3,
    keywords: ["lift", "elevator", "a block", "maintenance"],
    requiresRoom: false,
  },
  {
    id: "maint-lift-b",
    name: "Lift Maintenance - B Block",
    category: "PREVENTIVE_MAINTENANCE",
    department: "maintenance",
    duration: 60,
    priority: "medium",
    photoRequired: true,
    photoCount: 3,
    keywords: ["lift", "elevator", "b block", "maintenance"],
    requiresRoom: false,
  },
]

// Helper function for category labels
export const CATEGORY_LABELS: Record<TaskCategory, string> = {
  GUEST_REQUEST: "Guest Issue",
  ROOM_CLEANING: "Room Cleaning",
  COMMON_AREA: "Common Area",
  PREVENTIVE_MAINTENANCE: "Maintenance",
  TIME_SENSITIVE: "Time-Sensitive",
}

// Helper function for category colors
export const CATEGORY_COLORS: Record<TaskCategory, string> = {
  GUEST_REQUEST: "bg-accent text-accent-foreground border-border",
  ROOM_CLEANING: "bg-muted text-muted-foreground border-border",
  COMMON_AREA: "bg-secondary text-secondary-foreground border-border",
  PREVENTIVE_MAINTENANCE: "bg-muted/50 text-foreground border-border",
  TIME_SENSITIVE: "bg-primary text-primary-foreground border-border",
}
