-- This script intentionally left blank.
-- The legacy `shifts` table has been removed in favor of `shift_schedules`.
-- Keeping this placeholder prevents accidental reintroduction of obsolete inserts.
